{{- range $appName, $app := .Values.apps }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ lower $appName }}-deployment
  labels:
    app: {{ lower $appName }}
spec:
  replicas: {{ $app.replicas }}
  selector:
    matchLabels:
      app: {{ lower $appName }}
  template:
    metadata:
      labels:
        app: {{ lower $appName }}
    spec:
      containers:
        - name: {{ lower $appName }}-container
          image: {{ $.Values.global.account_id }}.dkr.ecr.{{ $.Values.global.region }}.amazonaws.com/{{ $.Values.global.env }}-{{ $.Values.global.project }}-{{ lower $appName }}-repo:{{ $app.image.tag }}
          ports:
            - containerPort: {{ $app.service.port }}
          env:
            {{- range $envName, $envValue := $app.env }}
            - name: {{ $envName }}
              value: "{{ $envValue }}"
            {{- end }}
---
{{- end }}
