{{- range $appName, $app := .Values.apps }}
{{- if $app.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ lower $appName }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: "nginx"
  rules:
    - http:
        paths:
          - path: {{ $app.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ lower $appName }}-service
                port:
                  number: {{ $app.service.port }}
---
{{- end }}
{{- end }}
