global:
  env: staging
  project: devops
  region: us-east-1
  account_id: "484907518629"

ingress-nginx:
  controller:
    service:
      type: NodePort
      nodePorts:
        http: 30080

apps:
  bird:
    replicas: 2
    image:
      tag: "latest"
    ingress:
      enabled: true
      path: "/"
    service:
      port: 4201
    env:
      PORT: 4201
      DEFAULT_IMAGE_URL: "https://www.pokemonmillennium.net/wp-content/uploads/2015/11/missingno.png"
      BIRD_IMAGE_API_URL: "http://birdimage-service:4200" # Internal K8s service URL
      BIRD_API_BASE_URL: "https://freetestapi.com/api/v1/birds/"

  birdImage:
    replicas: 2
    image:
      tag: "latest"
    ingress:
      enabled: false
    service:
      port: 4200
    env:
      PORT: 4200
      UNSPLASH_API_URL: "https://api.unsplash.com/search/photos"
      UNSPLASH_CLIENT_ID: "P1p3WPuRfpi7BdnG8xOrGKrRSvU1Puxc1aueUWeQVAI"
      DEFAULT_IMAGE_URL: "https://www.pokemonmillennium.net/wp-content/uploads/2015/11/missingno.png"
